FROM continuumio/anaconda3:latest

# Set working directory
WORKDIR /app

# Install dependencies for Radioconda
RUN yes | conda create -n radioconda -c conda-forge -c ryanvolz --only-deps radioconda
RUN conda init
RUN conda activate radioconda
#RUN mamba install --file https://github.com/ryanvolz/radioconda/releases/latest/download/radioconda-$(conda info | sed -n -e 's/^.*platform : //p').lock
RUN mamba install requests

# Copy the Radioconda configuration file (if you have one) - Optional
# COPY radioconda.yml .

# Set the entrypoint to start the Radioconda service
#ENTRYPOINT ["python", "-m", "radioconda.cli", "--config", "radioconda.yml"] 
#Use radioconda.yml to point the config file

